services:
  db:
    image: postgres:16.2
    env_file:
      - .env.local
    environment:
      - POSTGRES_PASSWORD=rijensayami00438
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hr-payroll
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
