import type { Metadata } from 'next';

import { ThemeProvider } from './providers';
import { lexend } from '../../font';
import { Toaster } from 'sonner';

import './globals.css';

export const metadata: Metadata = {
  title: 'HRMS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
      >
        <body className={`${lexend.variable}`}>{children}</body>
        <Toaster position={'top-right'} expand={true} richColors />
      </ThemeProvider>
    </html>
  );
}
